# AI Bootcamp
## Hour 1 — AI, Data, and Your First NumPy Arrays

In this first hour, we will build the foundation for the rest of the bootcamp.

By the end of this session, you will understand:
- What AI, Machine Learning, and Deep Learning mean
- Why data must be represented as numbers
- Why NumPy is essential for Machine Learning
- How to create and inspect arrays
- How to use indexing and slicing to work with datasets

## 1. AI vs Machine Learning vs Deep Learning

### Artificial Intelligence (AI)
AI is the broad idea of making computers perform tasks that usually require human intelligence.

### Machine Learning (ML)
Machine Learning is a subset of AI.  
Instead of writing every rule manually, we give data to the machine and let it learn patterns.

### Deep Learning (DL)
Deep Learning is a subset of Machine Learning that uses multi-layer neural networks.

### Simple hierarchy
AI → ML → DL

## 2. Real-World Examples

Machine Learning is already part of products we use every day:

- **Recommendation Systems**  
  Netflix and YouTube recommend movies or videos based on your behavior.

- **Chatbots and Generative AI**  
  OpenAI systems can generate text, answer questions, and help with coding.

- **Computer Vision**  
  Google and self-driving car systems can detect objects in images or video.

- **Fraud Detection**  
  Banks use ML to detect unusual transactions.

## 3. The Big Idea of Machine Learning

Machine Learning often follows this simple workflow:

**Data → Learn Pattern → Predict**

Example:
- Input: house size, number of rooms, age
- Output: house price

The model looks at past examples and learns a relationship between inputs and outputs.

## 4. Data as Numbers

Computers do not understand concepts like "house", "student", or "image" directly.

They understand numbers.

That means:
- A table becomes a matrix of numbers
- A single sample becomes a vector
- A dataset becomes an array

This is why NumPy is so important in Machine Learning.

## 5. Example: House Prices vs. Text for Chatbots
### Example A: Numerical Dataset (House Prices)
Suppose we have this dataset:

| Size | Rooms | Age | Price |
|------|-------|-----|-------|
| 2000 | 3 | 10 | 500000 |
| 1500 | 2 | 5  | 350000 |
| 1800 | 3 | 8  | 420000 |

In Machine Learning:
- the input columns are called **features**
- the output column is called the **target**

### Example B: Unstructured Text Dataset (Chatbots & LLMs)

Large Language Models (LLMs) and chatbots don't read text the way humans do. They require text to be converted into lists of numbers, known as **word/text embeddings** or **vectors**

Imagine a model translating semantic meanings into numerical coordinates:


| Word/Phrase | Meaning Dim 1 (Joy) | Meaning Dim 2 (Nature) | Meaning Dim 3 (Tech) |
|-------------|---------------------|------------------------|----------------------|
| \"AI model\"  | 0.05                | -0.12                  | 0.98                 |
| \"Sunny day\"| 0.91                | 0.85                   | -0.45                |
| \"Chatbot\"  | 0.12                | -0.08                  | 0.94                 |

By looking at these lists of numbers (vectors), an LLM can calculate that the vector for \"AI model\" is mathematically very close to \"Chatbot\", allowing it to understand context and generate smart responses!

## 6. Why NumPy?

Python lists are useful, but they are not enough for Machine Learning.

NumPy gives us:
- faster numerical computation
- easier array manipulation
- vectorized operations
- support for matrix and linear algebra operations

The core data structure in NumPy is called an **ndarray**.

## 7. Extra Learning Resource

For extra reading after class, see the official NumPy quickstart:

[NumPy Official Quickstart Guide](https://numpy.org/doc/stable/user/quickstart.html)

In [53]:
x = [1, 2, 3, 4]
print(x)

[1, 2, 3, 4]


In [30]:
import numpy as np

In [58]:
# A simple 1D array
a = np.array(x)
print(a)
print(type(a))
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>


## 4. Initialization: Common Ways to Create NumPy Arrays
While you can turn Python lists into arrays using `np.array()`, Machine Learning algorithms frequently require initializing arrays from scratch (e.g., creating blank matrices for weights, bias vectors set to zero, or tracking values over a linear range). 

Here are the 6 structural array creation tools you must know:
1. `np.array()`: Converts existing Python structures (like lists) into arrays.
2. `np.zeros(shape)`: Fills an array of a given shape with `0.0`. (Commonly used to initialize neural network *biases*).
3. `np.ones(shape)`: Fills an array of a given shape with `1.0`. 
4. `np.eye(n)`: Creates a 2D **Identity Matrix** of size $n \times n$ (ones on the main diagonal, zeros everywhere else).
5. `np.arange(start, stop, step)`: Creates a sequence of values with a defined *step size* (similar to Python's `range()`).
6. `np.linspace(start, stop, num)`: Creates a sequence with a specified *number of elements*, automatically calculating equal spacing.

In [32]:
import numpy as np

# 1. Custom Array from List
custom_arr = np.array([5, 10, 15])
print("1. np.array:\n", custom_arr)

1. np.array:
 [ 5 10 15]


In [61]:
# 2. Array of Zeros (Often used for Model Biases)
bias_vector = np.zeros(shape=(3,3,3)) 
print("\n2. np.zeros (1D vector):\n", bias_vector)


2. np.zeros (1D vector):
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [34]:
# 3. Matrix of Ones
ones_matrix = np.ones(shape=(2, 4))
print("\n3. np.ones (2x4 matrix):\n", ones_matrix)


3. np.ones (2x4 matrix):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
# 4. Identity Matrix
identity_matrix = np.eye(3)
print("\n4. np.eye (3x3 Identity):\n", identity_matrix)


4. np.eye (3x3 Identity):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
# 5. Arrange by Step Size
step_sequence = np.arange(start=0, stop=20, step=1)
print("\n5. np.arange [0 to 10, step 2]:\n", step_sequence)


5. np.arange [0 to 10, step 2]:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [67]:
# 6. Linspace by Number of Elements (Great for creating plotting intervals)
linear_intervals = np.linspace(start=0, stop=1, num=4)
print("\n6. np.linspace [0 to 1 split into 5 pieces]:\n", linear_intervals)


6. np.linspace [0 to 1 split into 5 pieces]:
 [0.         0.33333333 0.66666667 1.        ]


### 1D array = a vector

A 1D NumPy array is often used to represent one sample or one list of values.

In [74]:
# A simple 2D array
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.float64)
a = np.array(x)
print(a)
print("----------")
print(b)

[1 2 3 4]
----------
[[1. 2. 3.]
 [4. 5. 6.]]


### 2D array = a matrix

A 2D NumPy array is useful for representing datasets:
- rows = samples
- columns = features

In [75]:
print("a shape:", a.shape)
print("a ndim:", a.ndim)
print("a size:", a.size)
print("a dtype:", a.dtype)

a shape: (4,)
a ndim: 1
a size: 4
a dtype: int64


In [76]:
print("b shape:", b.shape)
print("b ndim:", b.ndim)
print("b size:", b.size)
print("b dtype:", b.dtype)

b shape: (2, 3)
b ndim: 2
b size: 6
b dtype: float64


## 8. Understanding Array Attributes

These are very important in Machine Learning:

- **shape**: tells us the dimensions of the array
- **ndim**: tells us how many dimensions the array has
- **size**: total number of elements
- **dtype**: type of the data inside the array

You will use `shape` constantly when debugging models.

In [41]:
# Creating arrays with helper functions
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
random_array = np.random.randn(2, 3)

print("zeros_array:\n", zeros_array)
print("\nones_array:\n", ones_array)
print("\nrandom_array:\n", random_array)

zeros_array:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones_array:
 [[1. 1. 1.]
 [1. 1. 1.]]

random_array:
 [[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]


## Computing  $sin(x)e^{-x}$

[sin(x[i]) * exp(-x[i]) for i in range(n)]

np.sin(x) * np.exp(-x)

In [77]:
import math

n = 100000
x = np.linspace(0, 2*np.pi, n)

# list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]
# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)

51.4 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.37 ms ± 138 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**What is Vectorization?**

Vectorization refers to one or both of the following, depending on the context, both of which are used in NumPy’s universal functions (ufuncs):

(1) Applying operations to all elements of a collection at once.

(2) Utilizing hardware instruction sets for parallel computation of a single instruction (SIMD).

In [78]:
def f(v): # apply f to one scalar value v
    return math.sin(v) * math.exp(-v)

vectorizedf = map(f, x) # معادل قابلیت اول موجود در نامپای

F = np.vectorize(f)

# list comprehension
%timeit y = [f(x[i]) for i in range(n)]

# use map
# %timeit y = list(vectorizedf)
%timeit y = list(map(f, x))

# use numpy's vectorize
%timeit y = F(x)

# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

46.3 ms ± 4.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
39.6 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
38.9 ms ± 611 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.14 ms ± 58.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 9. Creating Arrays in Different Ways

Common NumPy functions:
- `np.array(...)`
- `np.zeros(...)`
- `np.ones(...)`
- `np.random.randn(...)`

These are useful later for:
- initializing data
- creating placeholders
- initializing model parameters

## 10. Indexing

Indexing means accessing one specific element.

In [81]:
x = np.array([10, 20, 30, 40])

print(x[0])
print(x[2])
print(x[-1])
print(x[-2])

10
30
40
30


In [84]:
y = [1, 2, 3, 4]
print(y[-1])

4


## 11. Slicing

Slicing means selecting a range of elements.

In [86]:
x = np.array([10, 20, 30, 40])

print(x[0:2])
print(x[1:4])
print(x[:3])
print(x[2:])

[10 20]
[20 30 40]
[10 20 30]
[30 40]


## 12. Indexing and Slicing in 2D Arrays

In [91]:
dataset = np.array([
    [2000, 3, 10, 500000],
    [1500, 2, 5, 350000],
    [1800, 3, 8, 420000],
    [1900, 4, 10, 460000],
    [2200, 4, 12, 520000]
])

print(dataset)
print(dataset.shape)

[[  2000      3     10 500000]
 [  1500      2      5 350000]
 [  1800      3      8 420000]
 [  1900      4     10 460000]
 [  2200      4     12 520000]]
(5, 4)


In [97]:
print("First row:", dataset[0, :])
print("last row:", dataset[-1, :])
print("even rows:", dataset[0:5:2, :])
print("odd rows:", dataset[1:7:2, :])

print("All rows, first column:", dataset[:, 0])
print("First sample, second feature:", dataset[0, 1])
print("All rows, last column:", dataset[:, -1])

First row: [  2000      3     10 500000]
last row: [  2200      4     12 520000]
even rows: [[  2000      3     10 500000]
 [  1800      3      8 420000]
 [  2200      4     12 520000]]
odd rows: [[  1500      2      5 350000]
 [  1900      4     10 460000]]
All rows, first column: [2000 1500 1800 1900 2200]
First sample, second feature: 3
All rows, last column: [500000 350000 420000 460000 520000]


## 13. Splitting a Dataset into Features and Target

This is one of the most important uses of slicing in Machine Learning.

If the last column is the target:
- `X` = all rows, all columns except the last one
- `y` = all rows, only the last column

In [98]:
X = dataset[:, :-1]
y = dataset[:, -1]

print("X:\n", X)
print("\ny:\n", y)

X:
 [[2000    3   10]
 [1500    2    5]
 [1800    3    8]
 [1900    4   10]
 [2200    4   12]]

y:
 [500000 350000 420000 460000 520000]


Now we have:
- `X`: the input features
- `y`: the target values we want to predict

This simple slicing idea appears everywhere in data science and machine learning.

In [ ]:
print("X shape:", X.shape)
print("y shape:", y.shape)

## 14. Small Reflection

Look at the shapes:
- `X.shape` tells us how many samples and features we have
- `y.shape` tells us how many target values we have

This is the beginning of thinking like a machine learning engineer.

## 15. Altering Array Shapes & Random Initialization
In Machine Learning pipelines, raw data often doesn't match the dimensions your models or neural networks expect. We can alter shapes using `.reshape()` or `.T` (Transpose) to flip rows and columns. We also often initialize parameters using random distributions.

- `.reshape(rows, cols)`: Changes dimensions without changing the underlying data.
- `.T`: Transposes a 2D matrix (swaps rows and columns).
- `np.random.randn(rows, cols)`: Generates an array filled with random numbers from a standard normal distribution (mean=0, std=1)—essential for weight initializations.
- `np.random.seed(42)`: Fixes the random numbers generated so your code yields identical results every run.

In [ ]:
# Fix randomness for reproducible results
np.random.seed(42)

# Generate a flat vector of 6 elements
flat_data = np.array([10, 20, 30, 40, 50, 60])
print("Original Vector:", flat_data)

# Reshape into a 3x2 Matrix (3 rows, 2 features)
matrix_data = flat_data.reshape(3, 2)
print("\nReshaped into 3x2 Matrix:\n", matrix_data)

# Transpose the matrix into a 2x3 Matrix
print("\nTransposed Matrix (.T):\n", matrix_data.T)

# Generate a completely random weight matrix for a neural network
random_weights = np.random.randn(2, 3)
print("\nRandom Weight Matrix (2x3):\n", random_weights)

## 16. Mini Practice
Try these by yourself:

1. Create a NumPy array with values `[5, 10, 15, 20]`
2. Print its `shape`, `ndim`, and `size`
3. Create a `2 x 2` matrix
4. Print the first row of the matrix
5. Print the second column of the matrix
6. From the `dataset` above, extract only the feature matrix `X`

In [ ]:
# Write your answers here


## 17. Hour 1 Summary

In this hour, you learned:

- AI, ML, and Deep Learning are related but different
- Machine Learning learns patterns from data
- Data must be represented as numbers
- NumPy is the foundation for numerical computing in ML
- Arrays have important properties such as `shape`, `ndim`, `size`, and `dtype`
- Indexing and slicing let us read and split datasets

Next, we will move from arrays to **vectors**, and we will see how a single data sample can be treated as a mathematical object.