# Hour 3: Matrices, Broadcasting, and Data Preprocessing

Welcome to Hour 3! So far, we've worked with 1D arrays (Vectors). In Machine Learning, we almost never process one item at a time. Instead, we process data in batches. 

In this session, we will learn:
1. How ML models structure data (Matrices).
2. How to manipulate large datasets without slow `for` loops (Broadcasting).
3. How to prepare data for Neural Networks (Normalization).

## 1. Matrices as Datasets in ML

In the AI world, a dataset is a 2D array (a Matrix). The universal standard is:
- **Rows = Samples** (e.g., individual houses, different patients)
- **Columns = Features** (e.g., area, number of rooms, age of the house)

Let's create a mini-dataset of 3 houses. The features are: `[Area (sqm), Rooms, Age (years)]`.

In [1]:
import numpy as np

# Dataset: 3 houses, 3 features each
X = np.array([
    [120, 3, 10],  # House 1
    [85,  2, 5],   # House 2
    [200, 4, 20]   # House 3
])

print("Dataset X:\n", X)
print("\nShape of X:", X.shape) # Should be (3, 3) -> 3 rows, 3 columns

Dataset X:
 [[120   3  10]
 [ 85   2   5]
 [200   4  20]]

Shape of X: (3, 3)


## 2. The Magic of Broadcasting

What if we want to modify our data? For example, let's say due to a new zoning law, every house gets a 20 sqm garden added to its Area, but Rooms and Age stay the same.

In standard Python, you would write a `for` loop to go through every house. In NumPy, we use **Broadcasting**! NumPy automatically "stretches" a smaller array (a vector) to match a larger array (our matrix) so math operations happen instantly.

In [16]:
# The adjustment vector: +20 to Area, +0 to Rooms, +0 to Age
adjustment = np.array([20, 0, 0])

# NumPy broadcasts the vector to all 3 rows automatically!
X_adjusted = X + adjustment

print("Original Dataset:\n", X)
print("\nAdjusted Dataset (Broadcasting in action):\n", X_adjusted)
print(f"X:{X.shape}, adjustment:{adjustment.shape}, X_adjusted:{X_adjusted.shape}")

Original Dataset:
 [[2000    3   10]
 [1500    2    5]
 [1800    3    8]]

Adjusted Dataset (Broadcasting in action):
 [[2020    3   10]
 [1520    2    5]
 [1820    3    8]]
X:(3, 3), adjustment:(3,), X_adjusted:(3, 3)


## 2. The Magic of Broadcasting

What if we want to modify our data? For example, suppose a new zoning law gives every house an extra **20 square meters** of land. The **Area** should increase by 20, while **Rooms** and **Age** remain unchanged.

Without NumPy, we would need a `for` loop to update every row one by one. NumPy provides a much smarter solution called **Broadcasting**.

Broadcasting allows NumPy to automatically perform operations between arrays of different shapes, as long as their dimensions are compatible.

Suppose our feature matrix is:

In [5]:
X = np.array([
    [2000, 3, 10],
    [1500, 2, 5],
    [1800, 3, 8]
])

We create a vector that describes how each feature should change:

In [6]:
adjustment = np.array([20, 0, 0])


This vector means:

- **+20** → Add 20 to the Area
- **+0** → Do not change the number of Rooms
- **+0** → Do not change the Age

### Step 1: Original Shapes

```
X shape = (3, 3)

[[2000    3   10]
 [1500    2    5]
 [1800    3    8]]

adjustment shape = (3,)

[20   0   0]
```

Notice that `X` is a **3 × 3 matrix**, while `adjustment` is only a **1D vector**.

### Step 2: Broadcasting

NumPy automatically treats the vector as if it were copied to every row.

Conceptually, it behaves like this:

```
[[20   0   0]
 [20   0   0]
 [20   0   0]]
```

**Important:** NumPy does **not** actually create this larger array in memory. It only behaves as if it exists, making broadcasting both **fast** and **memory efficient**.

### Step 3: Element-wise Addition

Now NumPy adds corresponding elements:

```
[[2000    3   10]      [[20   0   0]
 [1500    2    5]   +   [20   0   0]
 [1800    3    8]]      [20   0   0]]
```

Result:

```
[[2020    3   10]
 [1520    2    5]
 [1820    3    8]]
```

In [7]:
# The adjustment vector: +20 to Area, +0 to Rooms, +0 to Age
adjustment = np.array([20, 0, 0])

# NumPy broadcasts the vector to every row automatically
X_adjusted = X + adjustment

print("Original Dataset:\n", X)
print("\nAdjusted Dataset:\n", X_adjusted)

Original Dataset:
 [[2000    3   10]
 [1500    2    5]
 [1800    3    8]]

Adjusted Dataset:
 [[2020    3   10]
 [1520    2    5]
 [1820    3    8]]


### Why Broadcasting is Powerful

Instead of writing loops, we simply write:

```python
X + adjustment
```

NumPy automatically applies the operation to every row, making the code:

- Shorter
- Easier to read
- Much faster than Python loops

## Broadcasting Rules

NumPy can perform operations on arrays with different shapes by following these rules:

### Rule 1: Compare Shapes from Right to Left

NumPy starts comparing the dimensions from the **last (rightmost)** dimension and moves to the left.

Example:

```
(3, 4)
   (4)
```

The last dimensions are both `4`, so they are compatible.

---

### Rule 2: Dimensions are Compatible if They are Equal

If two dimensions are the same, NumPy can operate on them.

Example:

```
(5, 3)
(5, 3)
```

Every dimension matches.

✅ Broadcasting works.

---

### Rule 3: A Dimension of 1 Can Be Stretched

If one dimension is `1`, NumPy automatically repeats it to match the other array.

Example:

```
(3, 4)
(1, 4)
```

```
(2, 3, 4)
(1, 1, 4)
```

```
(2, 3, 4)
(1, 4)
```

```
(2, 3, 4)
(,4)
```

```
(1, 3, 4)
(2,1,1)
```

The first dimension `1` is stretched to `3`.

Resulting shape:

```
(3, 4)
```

---

### Rule 4: Missing Dimensions are Treated as 1

If one array has fewer dimensions, NumPy assumes missing dimensions are `1`.

Example:

```
Matrix:  (3, 4)
Vector:     (4)
```

NumPy interprets the vector as:

```
(1, 4)
```

Then broadcasts it to:

```
(3, 4)
```

---

### Rule 5: Otherwise, Broadcasting Fails

If the dimensions are neither equal nor `1`, broadcasting is impossible.

Example:

```
(3, 4)
(2, 4)
```

The first dimensions are `3` and `2`.

❌ Neither is `1`, so NumPy raises a **ValueError**.

---

## Summary

Broadcasting works when, for every dimension (from right to left):

- ✅ The dimensions are equal, **or**
- ✅ One of the dimensions is `1`

Otherwise:

- ❌ Broadcasting is not possible.

## 3. Preprocessing: Mean Centering

Neural Networks get confused if features have wildly different scales (e.g., Area is around 100, but Rooms is around 3). 

One common fix is **Mean Centering**. The formula is:
$$ X_{centered} = X - \mu $$
(where $\mu$ is the mean of each feature).

**Crucial Concept: `axis=0`**
When calculating the mean of a matrix, we must tell NumPy *how* to calculate it. 
- `axis=0` means "calculate across rows" (giving us the mean of each column/feature).

In [3]:
# Calculate the mean of each feature (column)
feature_means = np.mean(X, axis=0)
print("Mean of [Area, Rooms, Age]:", feature_means)

# Use broadcasting to subtract the means from the entire dataset
X_centered = X - feature_means
print("\nMean-Centered Dataset:\n", X_centered)

# Notice how the values are now centered around zero!

Mean of [Area, Rooms, Age]: [135.           3.          11.66666667]

Mean-Centered Dataset:
 [[-15.           0.          -1.66666667]
 [-50.          -1.          -6.66666667]
 [ 65.           1.           8.33333333]]


## 4. Matrix Aggregations and the Power of `axis`
When working with feature matrices (Rows = Samples, Columns = Features), we frequently need to extract summary statistics like the mean, sum, or standard deviation.

- `np.mean(X)` or `X.mean()` without any arguments calculates the metric over the **entire matrix**.
- `axis=0`: Performs operations **down the columns** (collapsing rows). This gives you a statistic *per feature* (e.g., average age of all patients).
- `axis=1`: Performs operations **across the rows** (collapsing columns). This gives you a statistic *per sample* (e.g., average score across multiple tests for a single student).
- `keepdims=True`: Retains the original structural dimensions (preserves a 2D matrix shape), preventing common broadcasting dimension alignment errors.

In [12]:
# Create a dummy feature matrix: 3 samples, 2 features (e.g., [Age, Income])
X_features = np.array([
    [25, 50000],
    [45, 85000],
    [35, 60000]
])

# 1. Overall Mean
print("Overall Matrix Mean:", np.mean(X_features))

# 2. Per-feature Mean (Mean down columns)
feature_means = np.mean(X_features, axis=0)
print("Mean of each individual feature (Age mean, Income mean):", feature_means)

# 3. Structural safety using keepdims=True
safe_feature_means = np.mean(X_features, axis=0, keepdims=True)
print('\n--------------------------\n')
print("Feature mean without keepdims:", feature_means) # (2,) Vector
print("Feature mean shape without keepdims:", feature_means.shape) # (2,) Vector
print('\n--------------------------\n')
print("Feature mean with keepdims:", safe_feature_means)   # (1, 2) Matrix
print("Feature mean shape with keepdims:", safe_feature_means.shape)   # (1, 2) Matrix

Overall Matrix Mean: 32517.5
Mean of each individual feature (Age mean, Income mean): [3.5e+01 6.5e+04]

--------------------------

Feature mean without keepdims: [3.5e+01 6.5e+04]
Feature mean shape without keepdims: (2,)

--------------------------

Feature mean with keepdims: [[3.5e+01 6.5e+04]]
Feature mean shape with keepdims: (1, 2)


## 5. Mini-Project: Min-Max Scaling

Another very popular normalization technique is **Min-Max Scaling**. It shrinks all your data to fall perfectly between $0$ and $1$.

The formula is:
$$ X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}} $$

**Your Task:**
1. Find the minimum of each feature using `np.min(X, axis=0)`
2. Find the maximum of each feature using `np.max(X, axis=0)`
3. Apply the formula using Broadcasting!

In [4]:
# 1. Find the minimums (axis=0)
X_min = # YOUR CODE HERE

# 2. Find the maximums (axis=0)
X_max = # YOUR CODE HERE

# 3. Apply the formula
X_scaled = # YOUR CODE HERE

# --- SOLUTION (Uncomment below to check your work) ---
# X_min = np.min(X, axis=0)
# X_max = np.max(X, axis=0)
# X_scaled = (X - X_min) / (X_max - X_min)

print("Min-Max Scaled Dataset (Values should be between 0 and 1):\n", X_scaled)

SyntaxError: invalid syntax (744998119.py, line 2)

### Excellent Work!
You now know how to structure data as Matrices and how to preprocess them for AI models using Broadcasting. In Hour 4, we will introduce the **Dot Product** and see how a basic Artificial Neuron processes this data!