# Hour 06: Reshaping, Conditional Logic, and Activation Functions

In this session, we will cover two crucial data manipulation techniques in NumPy: reshaping data (often needed for images) and conditional replacement. We will then combine everything we've learned to build a complete forward pass of a neural network with a ReLU activation function and a Loss calculation.

In [2]:
import numpy as np

## 1. Shape Operations: Reshape and Transpose

In Machine Learning, your data's shape often doesn't perfectly match the shape your neural network expects. 

*   **Reshape (`np.reshape` or `.reshape()`)**: Changes the dimensions of an array without changing its data. A common use case is "flattening" a 2D image into a 1D vector.
*   **Transpose (`.T`)**: Swaps rows and columns. This is often used to align matrix inner dimensions for matrix multiplication.

In [ ]:
# Example: Flattening a 2x2 image into a 1D array of 4 pixels
image = np.array([
    [0.1, 0.9, 0.1],
    [0.8, 0.2, 0.2]
]) # Shape: (2, 3)

flattened_image = image.reshape(6) # -1 means "figure out the exact dimension automatically"
print("Original Image Shape:", image.shape)
print("Flattened Image:", flattened_image)
print("Flattened Shape:", flattened_image.shape)

print("-" * 30)

# Example: Transposing a Matrix
A = np.array([[1, 2, 3], [4, 5, 6]]) # Shape: (2, 3)
A_T = A.T                            # Shape: (3, 2)
print("Original A:\n", A)
print("Transposed A:\n", A_T)

In [19]:
A = np.arange(24).reshape(2, 3, -1)
print(A)
print(A.shape)
# (2, 3, 4)
print(A.T.shape)
# (4, 3, 2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
(4, 3, 2)


In [7]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2, 2)
print(f"b:{b}")
print(f"a:{a.shape}")
print(f"b:{b.shape}")


b:[[1 2]
 [3 4]]
a:(4,)
b:(2, 2)


In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(-1)
print(f"b:{b}")
print(f"a:{a.shape}")
print(f"b:{b.shape}")


b:[1 2 3 4 5 6]
a:(6,)
b:(6,)


## 2. Vectorized If-Else with `np.where`

Using Python `for` loops and `if` statements is too slow for large datasets. NumPy provides `np.where(condition, value_if_true, value_if_false)` to apply conditions across an entire array instantly.

In [20]:
data = np.array([-2, 5, -8, 10, -1])

# Replace all negative numbers with 0, and keep positive numbers as they are
cleaned_data = np.where(data < 0, 0, data) # cleaned_data = max(0, data)

print("Original Data:", data)
print("Cleaned Data: ", cleaned_data)

Original Data: [-2  5 -8 10 -1]
Cleaned Data:  [ 0  5  0 10  0]


## 3. ML Connection: The ReLU Activation Function

In neural networks, linear operations ($X @ W + b$) alone can only solve linear problems. To learn complex patterns, we pass the output through an **Activation Function**.

The most popular activation function is **ReLU (Rectified Linear Unit)**. 
Formula: $$ ReLU(x) = \max(0, x) $$
In simple terms: If the value is negative, make it $0$. If it's positive, leave it alone. This is perfectly handled by `np.where`!

In [ ]:
Z = np.array([[-1.5, 2.0, -0.5],
              [3.1, -2.2, 0.8]])

# Apply ReLU Activation
# A = np.where(Z > 0, Z, 0)
A = np.where(Z < 0, 0, Z)

print("Raw Output (Z):\n", Z)
print("\nActivated Output (A):\n", A)

## 🛠 A Complete Network Pass with Loss

Let's put everything together! We have a batch of 4 images, each $2 \times 2$ pixels. 

**Your Task:**
1. **Reshape**: Flatten the `X_batch` of images from `(4, 2, 2)` to `(4, 4)`.
2. **Linear Layer**: Calculate $Z = X \cdot W + b$.
3. **Activation**: Pass $Z$ through a ReLU function to get the predictions $\hat{y}$ (`y_hat`).
4. **Loss**: Calculate the Mean Squared Error (MSE) between `y_hat` and `y_true`. 
   Formula: $$ MSE = \frac{1}{N} \sum (\hat{y} - y)^2 $$

In [ ]:
np.random.seed(0)
X_batch = np.random.randn(4, 2, 2) # 4 images, 2x2 pixels
W = np.random.randn(4, 1)          # Weights: 4 inputs -> 1 output neuron
b = np.array([0.5])                # Bias

y_true = np.array([[1.0], [0.0], [1.0], [0.0]]) # True labels

# 1. Flatten the inputs
X_flat = ... # Hint: use .reshape(4, -1)

# 2. Linear Forward Pass
Z = ...

# 3. ReLU Activation (y_hat)
y_hat = ...

# 4. Calculate Mean Squared Error (MSE)
mse_loss = ... # Hint: use np.mean()

print("Predictions (y_hat):\n", y_hat)
print("MSE Loss:", mse_loss)

In [ ]:
import numpy as np

np.random.seed(0)
X_batch = np.random.randn(4, 2, 2)  # 4 images, 2x2 pixels
W = np.random.randn(4, 1)           # Weights: 4 inputs -> 1 output neuron
b = np.array([0.5])                 # Bias

y_true = np.array([[1.0], [0.0], [1.0], [0.0]])  # True labels

# 1. Flatten the inputs
X_flat = X_batch.reshape(4, -1)

# 2. Linear Forward Pass
Z = X_flat @ W + b

# 3. ReLU Activation (y_hat)
y_hat = np.maximum(0, Z)

# 4. Calculate Mean Squared Error (MSE)
mse_loss = np.mean((y_hat - y_true) ** 2)

print("Predictions (y_hat):\n", y_hat)
print("MSE Loss:", mse_loss)

## 4. Multi-Class Classification: Softmax & Structural Dimension Safety

While ReLU is great for hidden layers, multi-class classification networks require outputs to behave like probabilities (values between 0 and 1 that sum up to 1). For this, we use the **Softmax** activation function.

Formula for a vector element:
$$ Softmax(z_i) = \frac{e^{z_i}}{\sum e^{z_j}} $$

To calculate this across an entire batch matrix, we use exponential universal functions (`np.exp()`) combined with strict row-wise operations.

### The Crucial Role of `keepdims=True`
When summing probabilities across rows, omitting `keepdims=True` drops the 2D matrix structure, converting it into a 1D array. This causes subsequent matrix broadcasting to fail or apply incorrectly down columns instead of across rows.

In [ ]:
# Raw logits from a layer output: 2 samples, 3 classes
Z_logits = np.array([
    [2.0, 1.0, 0.1],
    [1.0, 3.0, 0.2]
])

# Step 1: Compute exponentials
exp_Z = np.exp(Z_logits)

# Step 2: Sum along rows (axis=1) keeping original 2D structural shape
sum_exp_Z = np.sum(exp_Z, axis=1, keepdims=True)

# Step 3: Use broadcasting to divide safely
probabilities = exp_Z / sum_exp_Z

print("Raw Matrix Shape:", Z_logits.shape)
print("Row Sum Matrix Shape (with keepdims=True):", sum_exp_Z.shape)
print("\nOutput Class Probabilities (Rows sum perfectly to 1.0):\n", probabilities)

## 5. Interpreting Predictions (`np.argmax`) & Memory Safety

### A. Turning Probabilities into Class Predictions
Once your network outputs final probabilities, use `np.argmax(axis=1)` to extract the index of the highest value in each row, yielding the final model classification.

In [24]:
# Simulated model probabilities for 3 samples across 3 classes
# تشخیص نوع وسیله نقلیه از روی تصویر
# خروجی شبکه یک سه تایی (سبک، سنگین، موتور سیکلت)
model_outputs = np.array([
    [0.1, 0.7, 0.2],  # Sample 1 -> Predicted Class Index 1
    [0.8, 0.05, 0.15], # Sample 2 -> Predicted Class Index 0
    [0.3, 0.2, 0.5]   # Sample 3 -> Predicted Class Index 2
])

max_scores = np.max(model_outputs, axis=1)
print("Max Scores for the Batch:", max_scores)

# Extract the index of the max value across the columns (axis=1)
predicted_classes = np.argmax(model_outputs, axis=1)
print("Predicted Class Labels for the Batch:", predicted_classes)

Max Scores for the Batch: [0.7 0.8 0.5]
Predicted Class Labels for the Batch: [1 0 2]


### B. Array Views vs. Copies
In NumPy, slicing or assigning an array variable does not create a new copy of the data. Instead, it creates a "View." Modifying a slice or batch assignment will inadvertently alter your original underlying dataset!

Use ```.copy()``` when you explicitly need to decouple intermediate variables or mini-batches from your primary dataset.

In [25]:
# Modifying a View (Dangerous Trap)
original_dataset = np.array([10, 20, 30, 40])
print("Original Dataset:", original_dataset)
view_slice = original_dataset[0:2]
view_slice[0] = 999
print("Original Dataset altered by view modification:", original_dataset)

Original Dataset: [10 20 30 40]
Original Dataset altered by view modification: [999  20  30  40]


In [27]:
# Modifying an Explicit Copy (Safe)
original_dataset = np.array([10, 20, 30, 40])
print("Original Dataset:", original_dataset)

safe_copy = original_dataset[0:2].copy()
safe_copy[0] = 999
print("Original Dataset preserved when using .copy():", original_dataset)

Original Dataset: [10 20 30 40]
Original Dataset preserved when using .copy(): [10 20 30 40]


In [28]:
# عملگرهایی که باعث میشوند ما یک آرایه نامپای جدید داشته باشیم از جنس ویو هستند یا کپی؟
