In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [7]:
b = np.array([
    [9,8,7],
    [6,3,5]
])
print(b)

[[9 8 7]
 [6 3 5]]


In [8]:
# Get dimention
a.ndim

1

In [9]:
# Get shape
b.shape

(2, 3)

In [10]:
# Get type
a.dtype

dtype('int16')

In [11]:
# Get size
a.itemsize

2

In [12]:
# Get total size
print(a.nbytes)
print(a.size * a.itemsize)

6
6


In [13]:
# How to change specific elements in an array
a = np.array([
    [ 1, 2, 3, 4, 5, 6, 7],
    [ 8, 9,10,11,12,13,14]
])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get specific element [row, column](It starts from 0)
a[1,5]

np.int64(13)

In [15]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 1]

array([2, 9])

In [17]:
# Getting a little more fancy [startindex: endindex: stepsize]
a[0,1:5:2]

array([2, 4])

In [18]:
a[1,5] = 20
print(a)
a[:,0] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 5  2  3  4  5  6  7]
 [ 5  9 10 11 12 20 14]]


In [21]:
# 3D example
b = np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
print(b)
print(b[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


In [ ]:
# All zeros matrix
a = np.zeros(3)
b = np.zeros((2,2))
c = np.zeros((2,3,4))
d = np.zeros((2,3,4,5))
print(a)


[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [28]:
# All 1s matrix
np.ones(2)

array([1., 1.])

In [31]:
# Any other number
arr = np.full((2,2),99)
print(arr)

[[99 99]
 [99 99]]


In [32]:
np.full_like(a,4)

array([4., 4., 4.])

In [36]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.94805563, 0.39811608],
       [0.29260396, 0.76418392],
       [0.2367355 , 0.34938792],
       [0.96399394, 0.82711102]])

In [37]:
# Random Integer values
np.random.randint(7,size=(3,3))

array([[5, 0, 1],
       [1, 6, 3],
       [2, 4, 4]], dtype=int32)

In [38]:
# Another random integer
np.random.randint(4,8,size=(4,3))

array([[6, 4, 6],
       [6, 6, 7],
       [6, 4, 5],
       [6, 4, 5]], dtype=int32)

In [40]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Exercise
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
